version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    command: gunicorn clubaccounting.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    restart: "no" # ✅ dist 빌드 후 종료

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
      - ./backend/media:/app/backend/media
    depends_on:
      - frontend
      - backend
    restart: always
