# Generated by Django 5.2.1 on 2025-05-19 12:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('grade', models.PositiveSmallIntegerField()),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='전화번호는 하이픈 없이 11자리 숫자로 입력해야 합니다. (예: 01012345678)', regex='^\\d{11}$')])),
                ('member_type', models.CharField(choices=[('undergrad', '재학생'), ('leave', '휴학생'), ('grad', '대학원생')], max_length=10)),
                ('has_paid', models.BooleanField(default=False)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('has_receipt', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('ocr_store_name', models.CharField(blank=True, max_length=100)),
                ('ocr_result_text', models.TextField(blank=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='core.transaction')),
            ],
        ),
    ]
