# Generated by Django 5.2.1 on 2025-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
