# Generated by Django 5.2.1 on 2025-05-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
