# Generated by Django 5.2.1 on 2025-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auditrequest_auditresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_reviewed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', '미완료'), ('in_progress', '진행중'), ('completed', '완료')], default='not_reviewed', max_length=20),
        ),
        migrations.DeleteModel(
            name='TransactionComment',
        ),
    ]
