# Generated by Django 5.2.1 on 2025-05-26 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_transaction_is_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditresponse',
            name='request',
        ),
        migrations.RemoveField(
            model_name='auditresponse',
            name='responder',
        ),
        migrations.CreateModel(
            name='AuditComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='AuditRequest',
        ),
        migrations.DeleteModel(
            name='AuditResponse',
        ),
    ]
