# Generated by Django 5.2.1 on 2025-05-26 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_auditresponse_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditcomment',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='auditcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='audit_comments/'),
        ),
        migrations.AlterField(
            model_name='auditcomment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_comments', to='core.transaction'),
        ),
    ]
