# Generated by Django 5.2.1 on 2025-05-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_author_auditcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_notice',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
