# Generated by Django 5.2.1 on 2025-05-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_evidencefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
