# Generated by Django 5.2.1 on 2025-05-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_evidencefile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencefile',
            name='description',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
