# Generated by Django 5.2.1 on 2025-06-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_evidencefile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='club_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
